mountaincar.gb: main.c mountaincar.c qlearning.c
	..\..\gbdk-win64\gbdk\bin\lcc.exe -o mountaincar.gb main.c mountaincar.c qlearning.c

mountaincar.exe: main.c mountaincar.c qlearning.c
	gcc -o mountaincar.exe main.c mountaincar.c qlearning.c
